In [1]:
from Mollification import *

from ex_lscm import *

import trimesh
import os
import time

import meshio as mio

from buildGlueMap import *
from getPatch import *

root_folder = os.getcwd()

In [2]:
# read paths from a text file, each line is a path
paths = []
# make sure encoding = "utf-16 le" for the tooNiceMeshPaths.txt file


# with open("filtering-thing10k/veryBadMeshPaths.txt", "r", encoding="utf-16") as f:
#     for line in f:
#         paths.append(line.strip())

with open("filtering-thing10k/x.txt", "r", encoding="utf-16") as f:
    for line in f:
        paths.append(line.strip())

# with open("filtering-thing10k/validMeshPaths.txt", "r", encoding="utf-16") as f:
#     for line in f:
#         paths.append(line.strip())

# with open("filtering-thing10k/tooNiceMeshPaths.txt", "r", encoding="utf-16") as f:
#     for line in f:
#         paths.append(line.strip())

# with open("filtering-thing10k/large_tooNiceMeshPaths.txt", "r", encoding="utf-16") as f:
#     for line in f:
#         paths.append(line.strip())
# with open("filtering-thing10k/large_kindaBadMeshPaths.txt", "r", encoding="utf-16") as f:
#     for line in f:
#         paths.append(line.strip())

# randomly order paths
import random
random.seed(42)
random.shuffle(paths)


print("Number of paths: ", len(paths))


Number of paths:  713


In [5]:
print(len(new_paths))

9


In [3]:
# filter out paths to be only paths that have boundary edges
new_paths = []
for i in range(len(paths)):
    try:
        mesh = mio.read("../../GC/" + paths[i])
        F = mesh.cells_dict["triangle"]
        V = mesh.points
    except:
        print("Error reading mesh: ", i, paths[i])
        continue

    if np.shape(F)[0] > 10000:
        continue

    if i > 1000:
        break

    if (i+1)%300 == 0:
        print("Processing mesh ", i+1, " out of ", len(paths), " Meshes: ", len(new_paths))

    # check if mesh has boundary
    # E = igl.boundary_facets(F)
    # if(len(E) > 0):
    new_paths.append(paths[i])

paths = new_paths

print("Number of paths with boundary: ", len(paths))
        

Error reading mesh:  175 Thingi10k\Thingi10k\raw_meshes\90089.obj
Processing mesh  600  out of  4489  Meshes:  426
Processing mesh  900  out of  4489  Meshes:  640
Number of paths with boundary:  714


In [4]:
# save paths to a text file
with open("filtering-thing10k/x.txt", "w", encoding="utf-16") as f:
    for path in paths:
        f.write(path + "\n")

In [28]:
mesh = mio.read("../../GC/" + paths[9])
F = mesh.cells_dict["triangle"]
V = mesh.points

FL = IntrinsicMollificationConstant(V, F, 1e-5)[-1]

V_uv = lscm_L(V, F, FL)[-1]

#print("V_uv" , V_uv)

qc = quasi_conformal_error(V, F, V_uv)[0]

print("qc", qc)



qc inf


In [3]:
delta = [1e-4, 1e-2] #, 1e-3, 1e-2, 1e-1]

def func(FL, G, delta, i):
    if i == 0:
        return FL, 0, 0
    elif i == 1:
        return IntrinsicMollificationFL(FL, G, delta, scheme=MOLLIFICATION_SCHEME.CONSTANT_EPSILON)
    elif i == 2:
        return IntrinsicMollificationFL(FL, G, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_STEP)
    elif i == 3:
        return IntrinsicMollificationFL(FL, G, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_INTERPOLATED)
    elif i == 4:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_MANHATTAN)
    elif i == 5:
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_EUCLIDEAN)
    elif i == 6:
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.GLOBAL_OPTIMIZATION_MANHATTAN)
    elif i == 7:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.GLOBAL_OPTIMIZATION_EUCLIDEAN)
    elif i == 8:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_STEP, pooling=MOLLIFICATION_POOLING.MEAN)
    elif i == 9:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_INTERPOLATED, pooling=MOLLIFICATION_POOLING.MEAN)
    elif i == 10:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_MANHATTAN, pooling=MOLLIFICATION_POOLING.MEAN)
    elif i == 11:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_EUCLIDEAN, pooling=MOLLIFICATION_POOLING.MEAN)
    elif i == 12:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_STEP, pooling=MOLLIFICATION_POOLING.MAX)
    elif i == 13:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_INTERPOLATED, pooling=MOLLIFICATION_POOLING.MAX)
    elif i == 14:        
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_MANHATTAN, pooling=MOLLIFICATION_POOLING.MAX)
    elif i == 15:
        return IntrinsicMollificationFL(FL, G, delta,  scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_EUCLIDEAN, pooling=MOLLIFICATION_POOLING.MAX)


time_glue = []

moll_labels = [
    "No Mollification",
    "Constant Epsilon",

    "One by One Step (Local)",
    "One by One Interpolated (Local)",
    "Local Least Mollification Manhattan (Local)",
    "Local Least Mollification Euclidean (Local)",

    "Global Least Mollification Manhattan",
    "Global Least Mollification Euclidean",

    "One by One Step (Global, Mean)",
    "One by One Interpolated (Global, Mean)",
    "Local Least Mollification Manhattan (Global, Mean)",
    "Local Least Mollification Euclidean (Global, Mean)",

    "One by One Step (Global, Max)",
    "One by One Interpolated (Global, Max)",
    "Local Least Mollification Manhattan (Global, Max)",
    "Local Least Mollification Euclidean (Global, Max)"
]

times = np.zeros((len(moll_labels), len(delta)))

n_moll = np.zeros((len(moll_labels), len(delta)))

n_iter = np.zeros((len(moll_labels), len(delta)))

avg_moll = np.zeros((len(moll_labels), len(delta)))

avg_moll_for_mollified_edges = np.zeros((len(moll_labels), len(delta)))

avg_qc = np.zeros((len(moll_labels), len(delta)))

n_qc_nan = np.zeros((len(moll_labels), len(delta)))


n = 0

for i in range(len(paths)):
    try:

        mesh = mio.read("../../GC/" + paths[i])
        F = mesh.cells_dict["triangle"]
        V = mesh.points

        # [V,F]= igl.read_triangle_mesh(os.path.join(
                    # root_folder, "../../GC/", paths[i]))
        print("Mesh ", i + 1, " out of ", len(paths), ". Number of vertices: ", len(V), ". Number of faces: ", len(F), ", eul = " , igl.euler_characteristic(F), "loop count: ", len(igl.all_boundary_loop(F)))

        # check if mesh has boundary
        # E = igl.boundary_facets(F)
        # if(len(E) == 0):
        #     continue

        start = time.time()
        G = build_gluing_map(F)
        end = time.time()
        time_glue.append(end - start)

        E = igl.boundary_facets(F)
        if(len(E) == 0): # if no boundary
            # delete 1 random face (row)
            #F = np.delete(F, np.random.randint(0, len(F)), 0)
            # Better? : use the glueing map and BFS to get a patch of faces
            # and use that as the mesh for parameterization instead of the whole mesh
            factor = 0.25

            F_Patch = get_patch(F, G, factor)
            # remove unused vertices
            V_Patch, F_Patch = igl.remove_unreferenced(V, F_Patch)[0:2]

            #print("1 xai = ", igl.euler_characteristic(F_Patch), "loop count: ", len(igl.all_boundary_loop(F_Patch)) , "mesh: " , i + 1, " path: ", paths[i])

            # TODO: check for manifoldness aswell.
            while igl.euler_characteristic(F_Patch) + len(igl.all_boundary_loop(F_Patch)) != 2:
                factor *= 0.99
                #print("2 xai = ", igl.euler_characteristic(F_Patch), "loop count: ", len(igl.all_boundary_loop(F_Patch)) , "mesh: " , i + 1, " path: ", paths[i])
                F_Patch = get_patch(F, G, factor)
                # remove unused vertices
                V_Patch, F_Patch = igl.remove_unreferenced(V, F_Patch)[0:2]

            F = F_Patch
            V = V_Patch

        
        else:
            F_Patch = F
            # print("3 xai = ", igl.euler_characteristic(F_Patch), "loop count: ", len(igl.all_boundary_loop(F_Patch)) , "mesh: " , i + 1, " path: ", paths[i])

            factor = 0.25

            while igl.euler_characteristic(F_Patch) + len(igl.all_boundary_loop(F_Patch)) != 2:
                factor *= 0.99
                # print("4 xai = ", igl.euler_characteristic(F_Patch), "loop count: ", len(igl.all_boundary_loop(F_Patch)) , "mesh: " , i + 1, " path: ", paths[i])
                F_Patch = get_patch(F, G, factor)
                V_Patch, F_Patch = igl.remove_unreferenced(V, F_Patch)[0:2]
            

            F = F_Patch
            V = V_Patch

        print("5 xai = ", igl.euler_characteristic(F), "loop count: ", len(igl.all_boundary_loop(F)) , "mesh: " , i + 1, " path: ", paths[i])



        # recalculate the gluing map for the new mesh (patch)
        G = build_gluing_map(F)

        FL0 = igl.edge_lengths(V, F)

        avg_edge_length = np.mean(FL0)

        for j in range(len(delta)):
            for k in range(len(moll_labels)):
                if k > 7:
                    continue
                # try:
                start = time.time()
                FL, nMoll, nIter = func(FL0, G, delta[j], k)
                end = time.time()
                times[k][j] += end - start
                n_moll[k][j] += nMoll / len(FL0 * 3)
                n_iter[k][j] += nIter

                V_uv = lscm_L(V, F, FL)[-1]
                qc = quasi_conformal_error(V, F, V_uv)[0]
                if np.isnan(qc) or np.isinf(qc):
                    n_qc_nan[k][j] += 1
                    qc = 50

                qc = min(qc, 50)

                avg_qc[k][j] += qc

                avg_moll[k][j] += np.sum(FL - FL0) / np.sum(FL0)
                if(nMoll > 0):
                    avg_moll_for_mollified_edges[k][j] += np.sum(FL - FL0) / (avg_edge_length * nMoll * 3)
                print(i + 1, j, k)
                # except:
                #     print("Error in mesh ", i + 1, " path: ", paths[i], " delta: ", delta[j], " mollification: ", moll_labels[k])
                #     continue

        n += 1
    except:
        print("Error reading mesh: ", i, paths[i])
        continue

    if((i + 1) % 4 == 0):
        print("Finished ", i + 1, " meshes.")
        print("Average time to glue: ", np.mean(time_glue), " Std dev time to glue: ", np.std(time_glue))
        print("_________________________________________________________")

        for j in range(len(delta)):
            for k in range(len(moll_labels)):
                if k > 7:
                    continue
                print("Delta: ", delta[j], " Mollification: ", moll_labels[k])
                print("Average time: ", times[k][j] / (n))
                print("Average number of mollified edges: ", n_moll[k][j] / (n))
                print("Average number of iterations: ", n_iter[k][j] / (n))
                print("Average mollification: ", avg_moll[k][j] / n)
                print("Average mollification for mollified edges: ", avg_moll_for_mollified_edges[k][j] / n)
                print("Average quasi conformal error: ", avg_qc[k][j] / (n))
                print("number of nan / inf qc: ", n_qc_nan[k][j])
                print("_________________________________________________________")


print("Finished All meshes.")
print("Average time to glue: ", np.mean(time_glue), " Std dev time to glue: ", np.std(time_glue))
print("_________________________________________________________")
for j in range(len(delta)):
    for k in range(len(moll_labels)):
        print("Delta: ", delta[j], " Mollification: ", moll_labels[k])
        print("Average time: ", times[k][j] / n)
        print("Average number of mollified edges: ", n_moll[k][j] / n)
        print("Average number of iterations: ", n_iter[k][j] / n)
        print("Average mollification: ", avg_moll[k][j] / n)
        print("Average mollification for mollified edges: ", avg_moll_for_mollified_edges[k][j] / n)
        print("Average quasi conformal error: ", avg_qc[k][j] / (n))
        print("number of nan / inf qc: ", n_qc_nan[k][j])
        print("_________________________________________________________")

Mesh  1  out of  713 . Number of vertices:  84 . Number of faces:  188 , eul =  -10 loop count:  0
5 xai =  0 loop count:  2 mesh:  1  path:  Thingi10k\Thingi10k\raw_meshes\100034.stl
1 0 0
1 0 1
1 0 2
1 0 3
1 0 4
1 0 5
1 0 6
1 0 7
1 1 0
1 1 1
1 1 2
1 1 3
1 1 4
1 1 5
1 1 6
1 1 7
Mesh  2  out of  713 . Number of vertices:  179 . Number of faces:  354 , eul =  2 loop count:  0
5 xai =  1 loop count:  1 mesh:  2  path:  Thingi10k\Thingi10k\raw_meshes\1344044.stl
2 0 0
2 0 1
2 0 2
2 0 3
2 0 4
2 0 5
2 0 6
2 0 7
2 1 0
2 1 1
2 1 2
2 1 3
2 1 4
2 1 5
2 1 6
2 1 7
Mesh  3  out of  713 . Number of vertices:  3164 . Number of faces:  6324 , eul =  2 loop count:  0
5 xai =  1 loop count:  1 mesh:  3  path:  Thingi10k\Thingi10k\raw_meshes\650178.stl
3 0 0
3 0 1
3 0 2
3 0 3
3 0 4
3 0 5
3 0 6
3 0 7
3 1 0
3 1 1
3 1 2
3 1 3
3 1 4
3 1 5
3 1 6
3 1 7
Mesh  4  out of  713 . Number of vertices:  2035 . Number of faces:  4086 , eul =  -8 loop count:  0
5 xai =  0 loop count:  2 mesh:  4  path:  Thingi10k\Thing

d:\4B\intrinsic_mollification\src\cotanLaplace.py:54: RuntimeWarning: divide by zero encountered in scalar divide
  wjk = (lengths[j] ** 2 + lengths[k] ** 2 - lengths[i] ** 2) / (8*area)
d:\4B\intrinsic_mollification\src\cotanLaplace.py:72: RuntimeWarning: invalid value encountered in scalar subtract
  Laplacian[fr[j], fr[j]] -= wjk  # L_jj
d:\4B\intrinsic_mollification\src\cotanLaplace.py:47: RuntimeWarning: invalid value encountered in sqrt
  area = np.sqrt(s*(s-e1)*(s-e2)*(s-e0))


16 0 4
16 0 5
16 0 6
16 0 7
16 1 0
16 1 1
16 1 2
16 1 3
16 1 4
16 1 5
16 1 6
16 1 7
Finished  16  meshes.
Average time to glue:  0.045935824513435364  Std dev time to glue:  0.04670865876296024
_________________________________________________________
Delta:  0.0001  Mollification:  No Mollification
Average time:  6.222724914550781e-05
Average number of mollified edges:  0.0
Average number of iterations:  0.0
Average mollification:  0.0
Average mollification for mollified edges:  0.0
Average quasi conformal error:  10.854302880310826
number of nan / inf qc:  1.0
_________________________________________________________
Delta:  0.0001  Mollification:  Constant Epsilon
Average time:  6.0424208641052246e-05
Average number of mollified edges:  0.4375
Average number of iterations:  1.0
Average mollification:  3.8580400134786944e-05
Average mollification for mollified edges:  3.8580400215154474e-05
Average quasi conformal error:  7.9388663878558114
number of nan / inf qc:  0.0
______________

d:\4B\intrinsic_mollification\src\cotanLaplace.py:73: RuntimeWarning: invalid value encountered in scalar subtract
  Laplacian[fr[k], fr[k]] -= wjk  # L_kk


19 0 0
19 0 1
19 0 2
19 0 3
19 0 4
19 0 5
19 0 6
19 0 7
19 1 0
19 1 1
19 1 2
19 1 3
19 1 4
19 1 5
19 1 6
19 1 7
Mesh  20  out of  713 . Number of vertices:  290 . Number of faces:  580 , eul =  0 loop count:  0
5 xai =  0 loop count:  2 mesh:  20  path:  Thingi10k\Thingi10k\raw_meshes\41509.stl
20 0 0
20 0 1
20 0 2
20 0 3
20 0 4
20 0 5
20 0 6
20 0 7
20 1 0
20 1 1
20 1 2
20 1 3
20 1 4
20 1 5
20 1 6
20 1 7
Finished  20  meshes.
Average time to glue:  0.04456225633621216  Std dev time to glue:  0.04466833372361598
_________________________________________________________
Delta:  0.0001  Mollification:  No Mollification
Average time:  4.978179931640625e-05
Average number of mollified edges:  0.0
Average number of iterations:  0.0
Average mollification:  0.0
Average mollification for mollified edges:  0.0
Average quasi conformal error:  15.179250906270195
number of nan / inf qc:  2.0
_________________________________________________________
Delta:  0.0001  Mollification:  Constant Epsilon
A

d:\4B\intrinsic_mollification\src\ex_lscm.py:162: RuntimeWarning: invalid value encountered in divide
  e2 = e2 / np.linalg.norm(e2)


22 0 1
22 0 2
22 0 3
22 0 4
22 0 5
22 0 6
22 0 7
22 1 0
22 1 1
22 1 2
22 1 3
22 1 4
22 1 5
22 1 6
22 1 7
Mesh  23  out of  713 . Number of vertices:  1229 . Number of faces:  2454 , eul =  2 loop count:  0
5 xai =  1 loop count:  1 mesh:  23  path:  Thingi10k\Thingi10k\raw_meshes\98021.stl
23 0 0
23 0 1
23 0 2
23 0 3
23 0 4
23 0 5
23 0 6
23 0 7
23 1 0
23 1 1
23 1 2
23 1 3
23 1 4
23 1 5
23 1 6
23 1 7
Mesh  24  out of  713 . Number of vertices:  1716 . Number of faces:  3428 , eul =  2 loop count:  0
5 xai =  -1 loop count:  3 mesh:  24  path:  Thingi10k\Thingi10k\raw_meshes\90434.stl
24 0 0
24 0 1
24 0 2
24 0 3
24 0 4
24 0 5
24 0 6
24 0 7
24 1 0
24 1 1
24 1 2
24 1 3
24 1 4
24 1 5
24 1 6
24 1 7
Finished  24  meshes.
Average time to glue:  0.04542406400044759  Std dev time to glue:  0.04102545729898141
_________________________________________________________
Delta:  0.0001  Mollification:  No Mollification
Average time:  4.1484832763671875e-05
Average number of mollified edges:  0.0
Aver

d:\4B\intrinsic_mollification\src\ex_lscm.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  return gamma_max / gamma_min, area_p


36 0 3
36 0 4
36 0 5
36 0 6
36 0 7
36 1 0
36 1 1
36 1 2
36 1 3
36 1 4
36 1 5
36 1 6
36 1 7
Finished  36  meshes.
Average time to glue:  0.04011007150014242  Std dev time to glue:  0.040560532775447834
_________________________________________________________
Delta:  0.0001  Mollification:  No Mollification
Average time:  2.765655517578125e-05
Average number of mollified edges:  0.0
Average number of iterations:  0.0
Average mollification:  0.0
Average mollification for mollified edges:  0.0
Average quasi conformal error:  12.26658836417174
number of nan / inf qc:  4.0
_________________________________________________________
Delta:  0.0001  Mollification:  Constant Epsilon
Average time:  5.4617722829182945e-05
Average number of mollified edges:  0.5277777777777778
Average number of iterations:  1.0
Average mollification:  4.365864623451325e-05
Average mollification for mollified edges:  4.36586460441704e-05
Average quasi conformal error:  9.57913495600747
number of nan / inf qc:  2.0
_

d:\4B\intrinsic_mollification\src\ex_lscm.py:167: RuntimeWarning: invalid value encountered in divide
  f2 = f2 / np.linalg.norm(f2)
d:\4B\intrinsic_mollification\src\ex_lscm.py:193: RuntimeWarning: invalid value encountered in sqrt
  gamma_min = np.sqrt(0.5 * (a + c - det))


90 0 0


d:\4B\intrinsic_mollification\src\ex_lscm.py:165: RuntimeWarning: invalid value encountered in divide
  f1 = v1 / np.linalg.norm(v1)


90 0 1
90 0 2
90 0 3
90 0 4
90 0 5
90 0 6
90 0 7
90 1 0
90 1 1
90 1 2
90 1 3
90 1 4
90 1 5
90 1 6
90 1 7
Mesh  91  out of  713 . Number of vertices:  1702 . Number of faces:  3404 , eul =  0 loop count:  0
5 xai =  0 loop count:  2 mesh:  91  path:  Thingi10k\Thingi10k\raw_meshes\110907.stl
91 0 0
91 0 1
91 0 2
91 0 3
91 0 4
91 0 5
91 0 6
91 0 7
91 1 0
91 1 1
91 1 2
91 1 3
91 1 4
91 1 5
91 1 6
91 1 7
Mesh  92  out of  713 . Number of vertices:  566 . Number of faces:  1152 , eul =  -10 loop count:  0
5 xai =  -3 loop count:  5 mesh:  92  path:  Thingi10k\Thingi10k\raw_meshes\96653.stl
92 0 0
92 0 1
92 0 2
92 0 3
92 0 4
92 0 5
92 0 6
92 0 7
92 1 0
92 1 1
92 1 2
92 1 3
92 1 4
92 1 5
92 1 6
92 1 7
Finished  92  meshes.
Average time to glue:  0.0405082106590271  Std dev time to glue:  0.047900797238462925
_________________________________________________________
Delta:  0.0001  Mollification:  No Mollification
Average time:  1.0822130286175272e-05
Average number of mollified edges:  0.0
Av

d:\4B\intrinsic_mollification\src\cotanLaplace.py:74: RuntimeWarning: invalid value encountered in scalar add
  Laplacian[fr[j], fr[k]] += wjk  # L_jk
d:\4B\intrinsic_mollification\src\cotanLaplace.py:75: RuntimeWarning: invalid value encountered in scalar add
  Laplacian[fr[k], fr[j]] += wjk  # L_kj


156 0 4
156 0 5
156 0 6
156 0 7
156 1 0
156 1 1
156 1 2
156 1 3
156 1 4
156 1 5
156 1 6
156 1 7
Finished  156  meshes.
Average time to glue:  0.047645267767783925  Std dev time to glue:  0.05649364868924927
_________________________________________________________
Delta:  0.0001  Mollification:  No Mollification
Average time:  6.382281963641827e-06
Average number of mollified edges:  0.0
Average number of iterations:  0.0
Average mollification:  0.0
Average mollification for mollified edges:  0.0
Average quasi conformal error:  8.91584261522509
number of nan / inf qc:  13.0
_________________________________________________________
Delta:  0.0001  Mollification:  Constant Epsilon
Average time:  7.8430542579064e-05
Average number of mollified edges:  0.44871794871794873
Average number of iterations:  1.0
Average mollification:  3.6719988741865826e-05
Average mollification for mollified edges:  3.671998859434508e-05
Average quasi conformal error:  7.478770286500082
number of nan / inf qc:

d:\4B\intrinsic_mollification\src\cotanLaplace.py:54: RuntimeWarning: invalid value encountered in scalar divide
  wjk = (lengths[j] ** 2 + lengths[k] ** 2 - lengths[i] ** 2) / (8*area)


216 0 0
216 0 1
216 0 2
216 0 3
216 0 4
216 0 5
216 0 6
216 0 7
216 1 0
216 1 1
216 1 2
216 1 3
216 1 4
216 1 5
216 1 6
216 1 7
Finished  216  meshes.
Average time to glue:  0.047039418308823196  Std dev time to glue:  0.05612415799753968
_________________________________________________________
Delta:  0.0001  Mollification:  No Mollification
Average time:  4.630865052688954e-06
Average number of mollified edges:  0.0
Average number of iterations:  0.0
Average mollification:  0.0
Average mollification for mollified edges:  0.0
Average quasi conformal error:  9.515473107263848
number of nan / inf qc:  21.0
_________________________________________________________
Delta:  0.0001  Mollification:  Constant Epsilon
Average time:  0.0001150974007539971
Average number of mollified edges:  0.4790697674418605
Average number of iterations:  1.0
Average mollification:  3.926934721776382e-05
Average mollification for mollified edges:  3.926934718607017e-05
Average quasi conformal error:  7.787776

d:\4B\intrinsic_mollification\src\ex_lscm.py:186: RuntimeWarning: invalid value encountered in divide
  Ss = (q[0] * (p[1][1] - p[2][1]) + q[1] * (p[2][1] - p[0][1]) + q[2] * (p[0][1] - p[1][1])) / area_p
d:\4B\intrinsic_mollification\src\ex_lscm.py:187: RuntimeWarning: invalid value encountered in divide
  St = (q[0] * (p[2][0] - p[1][0]) + q[1] * (p[0][0] - p[2][0]) + q[2] * (p[1][0] - p[0][0])) / area_p
d:\4B\intrinsic_mollification\src\ex_lscm.py:186: RuntimeWarning: divide by zero encountered in divide
  Ss = (q[0] * (p[1][1] - p[2][1]) + q[1] * (p[2][1] - p[0][1]) + q[2] * (p[0][1] - p[1][1])) / area_p
d:\4B\intrinsic_mollification\src\ex_lscm.py:187: RuntimeWarning: divide by zero encountered in divide
  St = (q[0] * (p[2][0] - p[1][0]) + q[1] * (p[0][0] - p[2][0]) + q[2] * (p[1][0] - p[0][0])) / area_p


225 0 5
225 0 6
225 0 7
225 1 0
225 1 1
225 1 2
225 1 3
225 1 4
225 1 5
225 1 6
225 1 7
Mesh  226  out of  713 . Number of vertices:  1312 . Number of faces:  2620 , eul =  2 loop count:  0
5 xai =  1 loop count:  1 mesh:  226  path:  Thingi10k\Thingi10k\raw_meshes\91606.stl
226 0 0
226 0 1
226 0 2
226 0 3
226 0 4
226 0 5
226 0 6
226 0 7
226 1 0
226 1 1
226 1 2
226 1 3
226 1 4
226 1 5
226 1 6
226 1 7
Mesh  227  out of  713 . Number of vertices:  2302 . Number of faces:  4600 , eul =  2 loop count:  0
5 xai =  1 loop count:  1 mesh:  227  path:  Thingi10k\Thingi10k\raw_meshes\93545.stl
227 0 0
227 0 1
227 0 2
227 0 3
227 0 4
227 0 5
227 0 6
227 0 7
227 1 0
227 1 1
227 1 2
227 1 3
227 1 4
227 1 5
227 1 6
227 1 7
Mesh  228  out of  713 . Number of vertices:  2031 . Number of faces:  4058 , eul =  2 loop count:  0
5 xai =  -4 loop count:  6 mesh:  228  path:  Thingi10k\Thingi10k\raw_meshes\98765.stl
228 0 0
228 0 1
228 0 2
228 0 3
228 0 4
228 0 5
228 0 6
228 0 7
228 1 0
228 1 1
228 1 2
228

In [ ]:
[V,F]= igl.read_triangle_mesh(os.path.join(
            # root_folder, "../../GC/TestEdgeLengths", "11.stl"))
            # root_folder, "../../GC/Thingi10K/Thingi10K/raw_meshes", "36069.stl"))
            # root_folder, "../../GC/Thingi10K/Thingi10K/raw_meshes", "93743.stl"))
            # root_folder, "../data", "goathead.obj"))
            root_folder, "../data", "dime_counting_tube.stl"))


In [ ]:
mesh = mio.read("../data/dime_counting_tube.stl")
F = mesh.cells_dict["triangle"]
V = mesh.points

In [ ]:
delta = 1e-2
FL = igl.edge_lengths(V, F)

In [ ]:
# time before
end0 = time.time()
FL1, nMoll1, _ = IntrinsicMollificationFL(FL, None, delta, scheme=MOLLIFICATION_SCHEME.CONSTANT_EPSILON)
end1 = time.time()
print("Constant Epsilon took: ", end1 - end0)

FL2, nMoll2, _ = IntrinsicMollificationFL(FL, None, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_STEP)
end2 = time.time()
print("One by one step took: ", end2 - end1)

FL3, nMoll3, _ = IntrinsicMollificationFL(FL, None, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_INTERPOLATED)
end3 = time.time()
print("One by one interpolated took: ", end3 - end2)

FL4, nMoll4, _ = IntrinsicMollificationFL(FL, None, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_MANHATTAN)
end4 = time.time()
print("Local least mollification Manhattan took: ", end4 - end3)

FL5, nMoll5, _ = IntrinsicMollificationFL(FL, None, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_EUCLIDEAN)
end5 = time.time()
print("Local least mollification Euclidean took: ", end5 - end4)

[0 1 0 0]
[0 2 0 2] >
[0 2 0 2]
[1 2 0 1] >
[1 2 0 1]
[3 4 1 0] >
[3 4 1 0]
[3 5 1 2] >
[3 5 1 2]
[4 5 1 1] >
[4 5 1 1]
[6 7 2 0] >
[6 7 2 0]
[6 8 2 2] >
[6 8 2 2]
[7 8 2 1] >
[7 8 2 1]
[ 9 10  3  0] >
[ 9 10  3  0]
[ 9 11  3  2] >
[ 9 11  3  2]
[10 11  3  1] >
[10 11  3  1]
[12 13  4  0] >
[12 13  4  0]
[12 14  4  2] >
[12 14  4  2]
[13 14  4  1] >
[13 14  4  1]
[15 16  5  0] >
[15 16  5  0]
[15 17  5  2] >
[15 17  5  2]
[16 17  5  1] >
[16 17  5  1]
[18 19  6  0] >
[18 19  6  0]
[18 20  6  2] >
[18 20  6  2]
[19 20  6  1] >
[19 20  6  1]
[21 22  7  0] >
[21 22  7  0]
[21 23  7  2] >
[21 23  7  2]
[22 23  7  1] >
[22 23  7  1]
[24 25  8  0] >
[24 25  8  0]
[24 26  8  2] >
[24 26  8  2]
[25 26  8  1] >
[25 26  8  1]
[27 28  9  0] >
[27 28  9  0]
[27 29  9  2] >
[27 29  9  2]
[28 29  9  1] >
[28 29  9  1]
[30 31 10  0] >
[30 31 10  0]
[30 32 10  2] >
[30 32 10  2]
[31 32 10  1] >
[31 32 10  1]
[33 34 11  0] >
[33 34 11  0]
[33 35 11  2] >
[33 35 11  2]
[34 35 11  1] >
[34 35 11  1]
[36 

IndexError: index 480 is out of bounds for axis 0 with size 480

In [ ]:
print(G)

In [ ]:
G = build_gluing_map(F)


end5 = time.time()

FL6, nMoll6, nIter6 = IntrinsicMollificationFL(L, G, delta, scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_STEP, pooling=MOLLIFICATION_POOLING.MEAN)
end6 = time.time()
print("Sequential global, one by one step, mean pooling took: ", end6 - end5)

 FL7, nMoll7, nIter7 = IntrinsicMollificationFL(L, G, delta, scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_INTERPOLATED, pooling=MOLLIFICATION_POOLING.MEAN)
 end7 = time.time()
 print("Sequential global, one by one interpolated, mean pooling took: ", end7 - end6)
 FL8, nMoll8, nIter8 = IntrinsicMollificationFL(L, G, delta, scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_MANHATTAN, pooling=MOLLIFICATION_POOLING.MEAN)
 end8 = time.time()
 print("Sequential global, local least mollification Manhattan, mean pooling took: ", end8 - end7)
 FL9, nMoll9, nIter9 = IntrinsicMollificationFL(L, G, delta, scheme=MOLLIFICATION_SCHEME.SEQUENTIAL_GLOBAL, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_EUCLIDEAN, pooling=MOLLIFICATION_POOLING.MEAN)
 end9 = time.time()
 print("Sequential global, local least mollification Euclidean, mean pooling took: ", end9 - end8)

1 27 27
2 108 135
3 33 168
4 36 204
5 36 240
6 35 275
7 35 310
8 35 345
9 35 380
10 35 415
11 35 450
12 35 485
13 35 520
14 35 555
15 35 590
16 35 625
17 35 660
18 34 694
19 34 728
20 34 762
21 33 795
22 33 828
23 33 861
24 30 891
25 25 916
26 22 938
27 11 949
28 6 955
29 3 958
30 1 959
31 0 959
Sequential global, one by one step, mean pooling took:  0.058502912521362305


In [ ]:
print("Constant Epsilon nMoll", nMoll1)
print("One by one step nMoll", nMoll2)
print("One by one interpolated nMoll", nMoll3)
print("Local least mollification Manhattan", nMoll4)
print("Local least mollification Euclidean", nMoll5) 
print("Sequential global, one by one step, mean pooling", nMoll6, "with", nIter6, "iterations")
print("Sequential global, one by one interpolated, mean pooling", nMoll7, "with", nIter7, "iterations")
print("Sequential global, local least mollification Manhattan, mean pooling", nMoll8, "with", nIter8, "iterations")
print("Sequential global, local least mollification Euclidean, mean pooling", nMoll9, "with", nIter9, "iterations")

Constant Epsilon nMoll 699466
One by one step nMoll 621
One by one interpolated nMoll 621
Local least mollification Manhattan 621
Local least mollification Euclidean 621
Sequential global, one by one step, mean pooling 621 with 2 iterations
Sequential global, one by one interpolated, mean pooling 621 with 2 iterations
Sequential global, local least mollification Manhattan, mean pooling 621 with 2 iterations
Sequential global, local least mollification Euclidean, mean pooling 621 with 2 iterations


In [ ]:
print(np.sum(FL1 - FL0) / np.sum(FL0))
print(np.sum(FL2 - FL0) / np.sum(FL0))
print(np.sum(FL3 - FL0) / np.sum(FL0))
print(np.sum(FL4 - FL0) / np.sum(FL0))
print(np.sum(FL5 - FL0) / np.sum(FL0))
print(np.sum(FL6 - FL0) / np.sum(FL0))
print(np.sum(FL7 - FL0) / np.sum(FL0))
print(np.sum(FL8 - FL0) / np.sum(FL0))
print(np.sum(FL9 - FL0) / np.sum(FL0))

0.009999969844763803
1.9515460139100948e-06
3.474920234048739e-06
1.9443048566123697e-06
1.9480259108943147e-06
1.9515460139100948e-06
3.474920234048739e-06
1.9443048566123697e-06
1.9480259108943147e-06


In [ ]:
F = np.array([F]).repeat(2, axis=0)
print(F.shape)

(2, 144046, 3)


In [ ]:
b = np.array([- delta,   - delta,    - delta,    0,     0,    0])
print(b, b[3])

[-0.1 -0.1 -0.1  0.   0.   0. ] 0.0


In [ ]:

print(times)
print(times[0][0])

[[[0.008999824523925781, 0.009971857070922852, 0.0074045658111572266, 0.007978677749633789, 0.007978200912475586, 0.007978677749633789, 0.006981372833251953, 0.0069806575775146484, 0.007978200912475586, 0.00698399543762207, 0.0020787715911865234, 0.01875782012939453, 0.012966156005859375, 0.20042777061462402, 0.21538996696472168, 0.22843718528747559, 0.24833154678344727, 0.22535395622253418, 0.23342514038085938, 0.2054445743560791, 0.22211956977844238, 0.22598624229431152, 0.21291351318359375, 0.22838973999023438, 0.2183852195739746, 0.2104785442352295, 0.0209505558013916, 0.0209810733795166, 0.02093958854675293, 0.02194070816040039, 0.02194833755493164, 0.020937442779541016, 0.02293872833251953, 0.024903535842895508, 0.02397322654724121, 0.023938894271850586, 0.020876646041870117, 0.025930166244506836, 0.025974512100219727, 0.042885780334472656, 0.04487967491149902, 0.044912099838256836, 0.04484891891479492, 0.05186605453491211, 0.04487323760986328, 0.040891408920288086, 0.04391884803

In [30]:
for j in range(len(delta)):
    for k in range(len(moll_labels)):
        print("Delta: ", delta[j], " Mollification: ", moll_labels[k])
        print("Average time: ", times[k][j] / n)
        print("Average number of mollified edges: ", n_moll[k][j] / n)
        print("Average number of iterations: ", n_iter[k][j] / n)
        print("Average mollification: ", avg_moll[k][j] / n)
        print("Average mollification for mollified edges: ", avg_moll_for_mollified_edges[k][j] / n)
        print("Average quasi conformal error: ", avg_qc[k][j] / (n - n_qc_nan[k][j]))
        print("number of nan / inf qc: ", n_qc_nan[k][j])
        print("_________________________________________________________")

Delta:  0.0001  Mollification:  No Mollification
Average time:  0.0
Average number of mollified edges:  0.0
Average number of iterations:  0.0
Average mollification:  0.0
Average mollification for mollified edges:  0.0
Average quasi conformal error:  6384.746159105442
number of nan / inf qc:  3.0
_________________________________________________________
Delta:  0.0001  Mollification:  Constant Epsilon
Average time:  0.0007948398590087891
Average number of mollified edges:  1.2
Average number of iterations:  1.2
Average mollification:  0.00011834390363984649
Average mollification for mollified edges:  0.0001183439035997586
Average quasi conformal error:  3625.336628588003
number of nan / inf qc:  3.0
_________________________________________________________
Delta:  0.0001  Mollification:  One by One Step (Local)
Average time:  0.02441372871398926
Average number of mollified edges:  0.04785941456973525
Average number of iterations:  1.2
Average mollification:  1.2700728747293424e-06
Aver