In [7]:
from Mollification import *

import trimesh
import os
import time

root_folder = os.getcwd()

In [10]:
[V,F]= igl.read_triangle_mesh(os.path.join(
            # root_folder, "../../GC/TestEdgeLengths", "11.stl"))
            root_folder, "../data", "bunny.obj"))


In [9]:
F = np.array([F]).repeat(2, axis=0)
print(F.shape)

(2, 144046, 3)


In [11]:
print(V, F)

[[-0.6301  1.4997 -0.5411]
 [-0.6205  1.5054 -0.5423]
 [-0.621   1.4978 -0.5417]
 ...
 [-0.1342  0.0502  0.5093]
 [-0.1636  0.0409  0.5287]
 [-0.176   0.04    0.5318]] [[    0     1     2]
 [    2     1     3]
 [    2     3     4]
 ...
 [63726 71981 63728]
 [71998 26888 26890]
 [26923 26922 72017]]


In [12]:
delta = 1e-2
print(igl.edge_lengths(V, F))
# time before
end0 = time.time()
IntrinsicMollification(V, F, delta, scheme=MOLLIFICATION_SCHEME.CONSTANT_EPSILON)
end1 = time.time()
print("Constant Epsilon took: ", end1 - end0)

IntrinsicMollification(V, F, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_STEP)
end2 = time.time()
print("One by one step took: ", end2 - end1)

IntrinsicMollification(V, F, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.ONE_BY_ONE_INTERPOLATED)
end3 = time.time()
print("One by one interpolated took: ", end3 - end2)

IntrinsicMollification(V, F, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_MANHATTAN)
end4 = time.time()
print("Local least mollification Manhattan took: ", end4 - end3)

IntrinsicMollification(V, F, delta, scheme=MOLLIFICATION_SCHEME.LOCAL_SCHEMES, local_scheme=MOLLIFICATION_LOCAL_SCHEME.LOCAL_LEAST_MOLLIFICATION_EUCLIDEAN)
end5 = time.time()
print("Local least mollification Euclidean took: ", end5 - end4)

[[0.00764003 0.00931558 0.01122898]
 [0.00820731 0.00641015 0.00764003]
 [0.00811049 0.00926553 0.00641015]
 ...
 [0.01277732 0.00597997 0.01115796]
 [0.0090802  0.01168161 0.01179619]
 [0.00956765 0.00732871 0.0069491 ]]
Constant Epsilon took:  0.017951250076293945
One by one step took:  0.6253283023834229
One by one interpolated took:  0.6612627506256104
Local least mollification Manhattan took:  6.644842147827148
Local least mollification Euclidean took:  27.817010164260864


In [8]:
b = np.array([- delta,   - delta,    - delta,    0,     0,    0])
print(b, b[3])

[-0.1 -0.1 -0.1  0.   0.   0. ] 0.0
